import type { Metadata } from "next";
import RouteHistoryTracker from "@/components/navigation/RouteHistoryTracker";
import "./globals.css";
import { Web3Provider } from "@/providers/Web3Provider";
import { Suspense } from "react";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col font-sans">
        <Web3Provider>
          <Suspense fallback={null}>
            <RouteHistoryTracker />
          </Suspense>
          <main className="flex min-h-screen flex-1 flex-col">
            {children}
          </main>
        </Web3Provider>
      </body>
    </html>
  );
}
