// lib/stellar/identity-registry.ts
//
// Soroban counterpart to the EVM `verifyIdentity` call in app/verify/success/page.tsx.
// Submits a real Noir UltraHonk proof to the on-chain `grant_identity_registry`,
// which cross-calls the `ultrahonk_verifier` to check it before recording the
// GitHub identity. Also exposes read helpers (is_verified / get_identity).
//
// Proof + public_inputs are the raw bb-generated byte blobs:
//   - proof:        bb `proof` file  (UltraHonk, keccak flavor, fixed length)
//   - publicInputs: bb `public_inputs` file (5 * 32 big-endian field bytes)
// Generate them with GrantOS-Soroban/scripts/gen-fixture.sh (bb 0.87.0), or via
// the backend proof endpoint — see GrantOS-Soroban/README.md.

import {
  Contract,
  TransactionBuilder,
  BASE_FEE,
  Address,
  xdr,
  nativeToScVal,
  scValToNative,
  rpc,
} from '@stellar/stellar-sdk';
import {
  getSorobanServer,
  STELLAR_NETWORK_PASSPHRASE,
  STELLAR_REGISTRY_ID,
  assertStellarConfigured,
} from './client';
import { signWithFreighter } from './freighter';

export interface StellarIdentity {
  is_verified: boolean;
  tier: number;
  github_id: bigint;
  created_year: number;
  github_handle: string;
}

function bytesScVal(bytes: Uint8Array): xdr.ScVal {
  return xdr.ScVal.scvBytes(Buffer.from(bytes));
}

/**
 * Submit a proof to `verify_identity`. Builds → simulates (prepare) → signs with
 * Freighter → sends → polls for success. Returns the transaction hash.
 */
export async function submitIdentityProof(params: {
  caller: string; // G… Freighter public key
  proof: Uint8Array;
  publicInputs: Uint8Array;
  githubHandle: string;
}): Promise<string> {
  assertStellarConfigured();
  const server = getSorobanServer();
  const contract = new Contract(STELLAR_REGISTRY_ID);

  const account = await server.getAccount(params.caller);
  const op = contract.call(
    'verify_identity',
    Address.fromString(params.caller).toScVal(),
    bytesScVal(params.proof),
    bytesScVal(params.publicInputs),
    nativeToScVal(params.githubHandle, { type: 'string' }),
  );

  const built = new TransactionBuilder(account, {
    fee: BASE_FEE,
    networkPassphrase: STELLAR_NETWORK_PASSPHRASE,
  })
    .addOperation(op)
    .setTimeout(60)
    .build();

  // Simulate to attach the Soroban footprint, resource fees and auth.
  const prepared = await server.prepareTransaction(built);

  const signedXdr = await signWithFreighter(prepared.toXDR(), params.caller);
  const signedTx = TransactionBuilder.fromXDR(signedXdr, STELLAR_NETWORK_PASSPHRASE);

  const sent = await server.sendTransaction(signedTx);
  if (sent.status === 'ERROR') {
    throw new Error(`Soroban sendTransaction failed: ${JSON.stringify(sent.errorResult)}`);
  }

  // Poll for final status.
  let result = await server.getTransaction(sent.hash);
  const deadline = Date.now() + 30_000;
  while (result.status === rpc.Api.GetTransactionStatus.NOT_FOUND && Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, 1500));
    result = await server.getTransaction(sent.hash);
  }
  if (result.status !== rpc.Api.GetTransactionStatus.SUCCESS) {
    throw new Error(`verify_identity did not succeed on-chain (status=${result.status}). ` +
      `The proof may be invalid or the github_id already registered.`);
  }
  return sent.hash;
}

/** Read-only: is this Stellar wallet verified? Mirrors EVM `isVerified`. */
export async function isVerifiedOnStellar(wallet: string): Promise<boolean> {
  // Pass the wallet as the simulation source — it's a funded G… account,
  // unlike the C… contract address which getAccount() can't fetch.
  return Boolean(await simulateRead('is_verified', [Address.fromString(wallet).toScVal()], wallet));
}

/** Read-only: full identity record, or null. Mirrors EVM `getIdentity`. */
export async function getIdentityOnStellar(wallet: string): Promise<StellarIdentity | null> {
  const native = await simulateRead('get_identity', [Address.fromString(wallet).toScVal()], wallet);
  return (native as StellarIdentity | null) ?? null;
}

/** Simulate a read-only contract call and decode the result to a native value.
 *  @param source  A funded G… account to use as the transaction source.
 *                 Defaults to the registry contract (may fail — prefer passing a G… address). */
async function simulateRead(method: string, args: xdr.ScVal[], source?: string): Promise<unknown> {
  assertStellarConfigured();
  const server = getSorobanServer();
  const contract = new Contract(STELLAR_REGISTRY_ID);
  const sourceAccount = await server.getAccount(source ?? STELLAR_REGISTRY_ID).catch(() => null);
  if (!sourceAccount) return null;

  const tx = new TransactionBuilder(sourceAccount, {
    fee: BASE_FEE,
    networkPassphrase: STELLAR_NETWORK_PASSPHRASE,
  })
    .addOperation(contract.call(method, ...args))
    .setTimeout(30)
    .build();

  const sim = await server.simulateTransaction(tx);
  if (rpc.Api.isSimulationError(sim) || !sim.result?.retval) return null;
  return scValToNative(sim.result.retval);
}
